### ISSUE TITLE
No primary detected for set cnf-serv

### ISSUE THREAD

**Issue by dukuo** [senssei/mongo-cluster-docker#3]
I keep getting the error even though I killed the instances as you suggested. Here's the console dump: 

[http://pastebin.com/dhdnMGyv](http://pastebin.com/dhdnMGyv)

I'm using Windows 10 with Docker version `1.13.1 build 092cba3`

Any idea why this keep happening?

Thanks!

**Comment by senssei** [comment]
Hi,

based on log it looks like Docker have no access to `scripts` files during setup first *Replica Set* called `mongo-cnf-setup_1 `.

```
mongo-cnf-setup_1    | standard_init_linux.go:178: exec user process caused "no such file or directory"
```

I know two Docker related reasons for that:

1. check line-ending in those files `init_shard.sh`,  `setup.sh`, `setup_cnf.sh` - the patch is prepared #4 or change them manually to `LF`, also global `git` config can mess this up - for example `autocrlf=true`
2. add your disk to *Shared Drives* in Docker - https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/9

Drop me a line, if this covers your case. Cheers.

**Comment by dukuo** [comment]
I think changing the lines to `LF` did the trick. Noob question, which instance should I use as the master from my app? mongo1-1 ? Thanks!

**Comment by senssei** [comment]
I would use `mongo-router` as main entry point from read and write concern. It is a little bit confusing, because in this setup I use both *Replication* and *Sharding* together. 

You could think about this like RAID 1+0. I've purposefully avoided to called any node *master*, because Mongo don't have multi-master https://docs.mongodb.com/manual/core/master-slave/.

Whole set is **sharded** environment, that's why on any databases and any collection you can create setup to share/split data across different *ReplicaSets*.

Additionally  `mongo-1-1` is  main entry point for *ReplicaSet1* and `mongo-2-1` is  main entry point for *ReplicaSet2*. Each *ReplicaSets* can elect their master and act as a fallback (with additional help from connection string options).

For more info, please referrer to https://docs.mongodb.com/manual/sharding/

**Comment by dukuo** [comment]
Clear as water. Thank you very much! I'm still learning replicating and sharding, and this is an excellent resource. Cheers

**Comment by dukuo** [comment]
i'm having the same issue again, but this time using elementary OS (16.04). Tried changing the files to `LF` but it didn't work. Do I need to mount any volumes? and if so, how could I do it? 

Thanks for the help so far

**Comment by senssei** [comment]
Do you have `+x` chmod on scripts ?

**Comment by dukuo** [comment]
Yup, checked twice for permissions on both the files and the scripts folder

**Comment by dukuo** [comment]
Now it's working. Apparently I had to open it with `sudo -i`. My apologies. 

Thank you!
