### ISSUE TITLE
Missing support for proper healthchecks

### ISSUE THREAD

**Issue by heycalmdown** [senssei/mongo-cluster-docker#6]
You are using the `curl` to setup the containers properly in synchronized from the scripts/*. But I can't find the `curl` in the recent official mongo images. The belows are what I tested.

```
mongo                              latest              5bc602c0b7fe        6 days ago          360 MB
mongo                              3.4.1               0dffc7177b06        2 months ago        402 MB
mongo                              3.3                 3abda4f46443        4 months ago        401 MB
mongo                              3.3.15              3abda4f46443        4 months ago        401 MB
mongo                              3.2.10              fe9198c04d62        4 months ago        342 MB
```

And

```bash
$ docker run -it --rm  mongo:3.3.15 curl
/entrypoint.sh: line 21: exec: curl: not found
```

Any advice?

**Comment by senssei** [comment]
Yep, you are right.

Because in official mongo images there isn't `curl` included https://github.com/docker-library/mongo/blob/master/3.4/Dockerfile .

This code is leftover from my early experimentation with custom mongo images. It's not required anymore. I've end up with going around this problem. Simply by trick with simply: 

- adding dependency with `depends_on:`,
- not putting `restart: always` on `mongo-xxx-setup`

It's working like a charm.

But, you can easily add `curl` 
 
```bash
docker run -it --rm  mongo bash
```
and then
```
apt-get update && apt-get install curl
```
or create own image with `curl` included (with Dockerfile).

l was planning rewrite it with docker `HEALTHCHECK` support, so pull requests are welcome.

**Comment by senssei** [comment]
Added _healthcheck_ using plain `mongo` without any need for `curl`.

```bash
echo "Waiting for startup.."
until mongo --host ${mongodb1}:${port} --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
  printf '.'
  sleep 1
done
```

Please see latest release https://github.com/senssei/mongo-cluster-docker/releases/tag/v1.0.0

**Comment by heycalmdown** [comment]
nice

**Comment by senssei** [comment]
Done.
